graph [
 Creator "makegml" directed 0 label ""
  node [ id 1 ]
  node [ id 2 ]
  node [ id 3 ]
  node [ id 4 ]
  node [ id 5 ]
  node [ id 6 ]
  node [ id 7 ]
  node [ id 8 ]
  node [ id 9 ]
  node [ id 10 ]
  node [ id 11 ]
  node [ id 12 ]
  node [ id 13 ]
edge [ source 1 target 2 ]
edge [ source 1 target 3 ]
edge [ source 1 target 4 ]
edge [ source 1 target 5 ]
edge [ source 1 target 6 ]
edge [ source 1 target 7 ]
edge [ source 1 target 8 ]
edge [ source 1 target 9 ]
edge [ source 1 target 10 ]
edge [ source 1 target 11 ]
edge [ source 1 target 12 ]
edge [ source 1 target 13 ]
]
