/*
 * BioModels Database: Web Services client library
 * Copyright (C) BioModels.net  2005-2012
 *
 *
 * The BioModels Database Web Services client library is free software:
 * you can redistribute it and/or modify it under the terms of the
 * GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
package de.ipk_gatersleben.ag_nw.graffiti.plugins.gui.layout_control.biomodels;

/**
 * Simple Model of a model from the Biomodels database, used to collect important meta-data for later
 * use.
 * @vanted.revision 2.8.3
 */

public class SimpleModel
{
    private final String id;
    private final String name;
    private String submitter;
    private String lastModificationDate;


    /**
     * Constructor (builds a partial object).
     * @param id model identifier
     * @param name model name
     */
    public SimpleModel(String id, String name)
    {
        this.id = id;
        this.name = name;
    }


    /**
     * Constructor (builds a complete object).
     * @param id model identifier (e.g. BIOMD0000000300)
     * @param name model name
     * @param submitter name of the submitter
     * @param lastModificationDate date of last modification (expressed according to ISO 8601, e.g. "2012-01-19T19:22:15+00:00")
     */
    public SimpleModel(String id, String name, String submitter, String lastModificationDate)
    {
        this.id = id;
        this.name = name;
        this.submitter = submitter;

        try
        {
            lastModificationDate = lastModificationDate.replace("Z","");
            this.lastModificationDate = lastModificationDate.replace("T", " ");
        }
        catch (Exception e)
        {
            this.lastModificationDate = null;
        }
    }


    /**
     * Returns a hash code value for this object.
     * Generated by Eclipse.
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode()
    {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        result = prime * result + ((lastModificationDate == null) ? 0 : lastModificationDate.hashCode());
        result = prime * result + ((name == null) ? 0 : name.hashCode());

        return result;
    }


    /**
     * Indicates whether some other object is "equal to" this one.
     * Partially generated by Eclipse.
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (obj == null) {
            return false;
        }

        if (getClass() != obj.getClass()) {
            return false;
        }

        SimpleModel other = (SimpleModel) obj;
        if (id == null) {
            if (other.id != null) {
                return false;
            }
        } else if (!id.equals(other.id)) {
            return false;
        }

        if (lastModificationDate == null) {
            if (other.lastModificationDate != null) {
                return false;
            }
        } else if (!lastModificationDate.equals(other.lastModificationDate)) {
            return false;
        }

        if (name == null) {
            if (other.name != null) {
                return false;
            }
        } else if (!name.equals(other.name)) {
            return false;
        }
        return false;
    }


    /**
     * Returns a string representation of the object.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString()
    {

        return "Identifier: " + this.id + "\n" +
                "Name: " + this.name + "\n" +
                "Submitter: " + this.submitter + "\n" +
                "Last modified: " + this.getLastModificationDateStr() + "\n";
    }


    /**
     * Get model identifier
     * @return model identifier
     */
    public String getId()
    {
        return this.id;
    }


    /**
     * Get the model name
     * @return model name
     */
    public String getName()
    {
        return this.name;
    }


    /**
     * Get the date of last modification, in a human readable form.
     * @return date of last modification
     */
    public String getLastModificationDateStr() { return this.lastModificationDate; }


    /**
     * Get names of the authors of the publication
     * @return the authors
     */
    public String getSubmitter()
    {
        return this.submitter;
    }
}

