// ==============================================================================
//
// View3D.java
//
// Copyright (c) 2001-2004 Gravisto Team, University of Passau
//
// ==============================================================================
// $Id: View3D.java,v 1.3 2010/12/14 07:02:13 morla Exp $

/* Generated by Together */
package org.graffiti.plugin.view;

/**
 * DOCUMENT ME!
 * 
 * @author $Author: morla $
 * @version $Revision: 1.3 $
 */
public interface View3D extends View {
}

// ------------------------------------------------------------------------------
// end of file
// ------------------------------------------------------------------------------
