package org.vanted.plugins.layout.multilevelframework;

import de.ipk_gatersleben.ag_nw.graffiti.plugins.gui.webstart.Main;

/**
 * Starts VANTED with the MLF add-on.
 * This is used for testing and debugging.
 * The end-users will use the JAR generated by the build-mlf-add-on.xml
 */
public class StartVantedWithAddon {
	
	/**
	 * Starts VANTED with the MLF add-on.
	 * 
	 * @param args
	 *           Passed to {@link Main#startVanted(String[], String)}
	 */
	public static void main(String[] args) {
//        String addOnName = "MLF-Add-On.xml";
//        System.out.println("Starting VANTED with Add-on " + addOnName + " for development...");
		Main.startVanted(args, null); //now part of the core
	}
}
